### ISSUE TITLE
Checks do not run

### ISSUE THREAD

**Issue by japborst** [athackst/htmlproofer-action#15]
Hello!

Thanks for providing this GH action :)!

Unfortunately, it seems that no checks are running.
```
{:check_external_hash=>false, :checks=>[], :ignore_empty_alt=>false, :enforce_https=>true, :hydra=>{:max_concurrency=>50}, :parallel=>{:in_processes=>3}, :typhoeus=>{:connecttimeout=>30, :followlocation=>true, :headers=>{"User-Agent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.0.0 Safari/537.36"}, :ssl_verifypeer=>false, :ssl_verifyhost=>0, :timeout=>120}, :ignore_urls=>["https://fonts.gstatic.com/"], :url_swap=>{/^\/error-prone-support/=>""}}
Running 0 checks () in ["./_site"] on *.html files...
```

This is my definition
```yaml
- name: Validating HTML output
  uses: athackst/htmlproofer-action@main
  with:
    check_external_hash: false
```

Thanks.
