### ISSUE TITLE
Links check is not run

### ISSUE THREAD

**Issue by roman-vasylenko** [athackst/htmlproofer-action#31]
Hi,

Thanks for the action. It does not seem to check links. There is at least one link in HTML files in _site directory with a bad anchor which is not detected.

```
{:allow_missing_href=>true, :check_external_hash=>true, :checks=>["Images", "Scripts"], :ignore_empty_alt=>true, :enforce_https=>false, :hydra=>{:max_concurrency=>50}, :typhoeus=>{:connecttimeout=>30, :followlocation=>true, :headers=>{"User-Agent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.0.0 Safari/537.36"}, :ssl_verifypeer=>false, :ssl_verifyhost=>0, :timeout=>120, :cookiefile=>".cookies", :cookiejar=>".cookies"}, :ignore_urls=>["********", "********"], :swap_urls=>{/^\/*******/=>"", /^.**********=>""}}
Running 2 checks (Images, Scripts) in ["./_site"] on *.html files ...
```

Workflow output:

```
Checking 4 external links
Checking 0 internal links
Checking internal link hashes in 0 files
Ran on 53492 files!


HTML-Proofer finished successfully.
```

My config:

```yml
uses: athackst/htmlproofer-action@main
        with:
          directory: ./_site
          allow_missing_href: true
          empty_alt_ignore: true
          enforce_https: false
          check_favicon: false
          check_html: false
          check_opengraph: false
```
