### ISSUE TITLE
empty_alt_ignore is not working

### ISSUE THREAD

**Issue by patrickelectric** [athackst/htmlproofer-action#55]
I'm getting:
```
* At ./ping-viewer/notifications-and-updates/index.html:700:

  image /ping-viewer/images/icons/close.png does not have an alt attribute

* At ./ping-viewer/notifications-and-updates/index.html:700:

  image /ping-viewer/images/icons/clear.png does not have an alt attribute

For the Links > External check, the following failures were found:
```

With the following configuration

```
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@v0.2.0
        with:
          directory: "."
          empty_alt_ignore: true
          ignore_urls: |
            https://fonts.gstatic.com
```
